version: "3.8"

services:
  web:
    container_name: example-frontend
    build:
      context: ./example-frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  backend:
    container_name: example-backend
    build:
      context: ./example-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
