version: "3.8"

services:
  web:
    container_name: simple_web_service
    image: devopsdockeruh/simple-web-service
    build: .
    ports:
      - 8080:8080
    command: server
    environment:
      - GIN_MODE=release
